/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.upiita.view;

import AppPackage.AnimationClass;
import com.upiita.dao.DirectorDAO;
import com.upiita.dao.sql.SQLDirectorDAO;
import com.upiita.view.fonts.Fuentes;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableRowSorter;
import com.upiita.model.Director;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author jessl
 */
public class _Directores extends javax.swing.JPanel {

    /**
     * Creates new form _Directores
     */
    
        private TableRowSorter sorter;
        private List<Director> directores;
        private DirectorDAO directorDao;
         
     
    public _Directores() throws FontFormatException {
        initComponents();
        
        bdel.setVisible(true);
        bedit.setVisible(true);
        
        Font LemonB = fonttype.nFont(fonttype.getLemon(), 1, 5);
        Font LemonB2 = fonttype.nFont(fonttype.getLemonB(), 1,6);
        Font Glacial = fonttype.nFont(fonttype.getGlacial() , 1,12);
        Font Lovelo = fonttype.nFont(fonttype.getLovelo() , 1,26);
        
        TBDirectores.setAlignmentX(10);
        TBDirectores.setFont(Glacial);
        headersDirectores();
        jScrollPane1.getViewport().setBackground(new Color(58,80,107));
        
        txtAltas.setFont(Lovelo);
        txtName.setFont(Glacial);
        btnAlta.setFont(LemonB2);
        txtBusqueda.setFont(Glacial);
        txtNombreEdit.setFont(LemonB);
        Label.setFont(Glacial);
                
        try{
            
            directorDao = new SQLDirectorDAO();
                    
            this.directores = directorDao.readAll();
        }
        catch(Exception xxx){
            xxx.printStackTrace();
            this.directores = new ArrayList<>();
        }
        
        this.fillDirectores();
        sorter = new TableRowSorter(TBDirectores.getModel());
        TBDirectores.setRowSorter(sorter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bdel = new javax.swing.JPanel();
        idel = new javax.swing.JLabel();
        bedit = new javax.swing.JPanel();
        iedit = new javax.swing.JLabel();
        breactivar = new javax.swing.JPanel();
        ireactivar = new javax.swing.JLabel();
        _Display = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBDirectores = new javax.swing.JTable();
        panelAdd = new javax.swing.JPanel();
        txtAltas = new javax.swing.JLabel();
        btnAlta = new javax.swing.JButton();
        txtNombreEdit = new javax.swing.JTextField();
        txtName = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        Label = new javax.swing.JLabel();

        setBackground(new java.awt.Color(58, 80, 107));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(28, 37, 65));
        jPanel1.setPreferredSize(new java.awt.Dimension(830, 50));
        jPanel1.setLayout(null);

        bdel.setBackground(new java.awt.Color(28, 37, 65));
        bdel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bdelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bdelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bdelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bdelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bdelMouseReleased(evt);
            }
        });
        bdel.setLayout(null);

        idel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/upiita/view/Resources/minus-square-solid.png"))); // NOI18N
        bdel.add(idel);
        idel.setBounds(10, 10, 30, 30);

        jPanel1.add(bdel);
        bdel.setBounds(10, 0, 50, 50);

        bedit.setBackground(new java.awt.Color(28, 37, 65));
        bedit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                beditMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                beditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                beditMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                beditMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                beditMouseReleased(evt);
            }
        });
        bedit.setLayout(null);

        iedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/upiita/view/Resources/pen-square-solid.png"))); // NOI18N
        bedit.add(iedit);
        iedit.setBounds(10, 10, 30, 30);

        jPanel1.add(bedit);
        bedit.setBounds(60, 0, 50, 50);

        breactivar.setBackground(new java.awt.Color(28, 37, 65));
        breactivar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                breactivarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                breactivarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                breactivarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                breactivarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                breactivarMouseReleased(evt);
            }
        });
        breactivar.setLayout(null);

        ireactivar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/upiita/view/Resources/reactivar.png"))); // NOI18N
        breactivar.add(ireactivar);
        ireactivar.setBounds(10, 10, 30, 30);

        jPanel1.add(breactivar);
        breactivar.setBounds(110, 0, 50, 50);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        _Display.setBackground(new java.awt.Color(58, 80, 107));
        _Display.setLayout(null);

        TBDirectores.setBackground(new java.awt.Color(58, 80, 107));
        TBDirectores.setForeground(new java.awt.Color(255, 255, 255));
        TBDirectores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"ALAIN MAGROU ", "1", null},
                {"ZORAN CALIC ", "2", null},
                {"ZLATKO LAVANIC", "3", null},
                {"YASUJI MARI", "4", null},
                {"WLADYSLAW PASIKOWSKI", "5", null},
                {"WILLIAM NIGH", "6", null},
                {"A. EDWARD SUTHERLAND", "7", null},
                {"AARÓN FERNÁNDEZ", "8", null},
                {"AARÓN ROMERA", "9", null},
                {"BEATRIZ FLORES SILVA", "10", null},
                {"BAZ LUHRMANN", null, null}
            },
            new String [] {
                "Director", "ID", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBDirectores.setGridColor(new java.awt.Color(58, 80, 107));
        TBDirectores.setOpaque(false);
        TBDirectores.setUpdateSelectionOnSort(false);
        jScrollPane1.setViewportView(TBDirectores);

        _Display.add(jScrollPane1);
        jScrollPane1.setBounds(50, 100, 300, 350);

        panelAdd.setBackground(new java.awt.Color(58, 80, 107));
        panelAdd.setLayout(null);

        txtAltas.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        txtAltas.setForeground(new java.awt.Color(255, 255, 255));
        txtAltas.setText("Altas Directores");
        txtAltas.setName("txtAltas"); // NOI18N
        panelAdd.add(txtAltas);
        txtAltas.setBounds(40, 20, 290, 60);

        btnAlta.setBackground(new java.awt.Color(28, 37, 65));
        btnAlta.setForeground(new java.awt.Color(255, 255, 255));
        btnAlta.setText("Alta");
        btnAlta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAltaMouseClicked(evt);
            }
        });
        btnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaActionPerformed(evt);
            }
        });
        panelAdd.add(btnAlta);
        btnAlta.setBounds(137, 170, 100, 40);

        txtNombreEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreEditActionPerformed(evt);
            }
        });
        panelAdd.add(txtNombreEdit);
        txtNombreEdit.setBounds(110, 110, 220, 24);

        txtName.setForeground(new java.awt.Color(255, 255, 255));
        txtName.setText("Nombre");
        panelAdd.add(txtName);
        txtName.setBounds(20, 110, 80, 30);

        _Display.add(panelAdd);
        panelAdd.setBounds(450, 120, 350, 230);

        txtBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaActionPerformed(evt);
            }
        });
        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyReleased(evt);
            }
        });
        _Display.add(txtBusqueda);
        txtBusqueda.setBounds(120, 50, 230, 24);

        Label.setForeground(new java.awt.Color(255, 255, 255));
        Label.setText("Buscar");
        _Display.add(Label);
        Label.setBounds(50, 50, 60, 16);

        add(_Display, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void bdelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bdelMouseEntered
        ImageIcon ic = new ImageIcon(getClass().getResource("/com/upiita/view/resources/minus-square-solid2.png"));
        idel.setIcon(ic);
        bdel.setBackground(Bchange);
    }//GEN-LAST:event_bdelMouseEntered

    private void bdelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bdelMouseExited
        ImageIcon ic = new ImageIcon(getClass().getResource("/com/upiita/view/resources/minus-square-solid.png"));
        idel.setIcon(ic);
        bdel.setBackground(Bback);
    }//GEN-LAST:event_bdelMouseExited

    private void beditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beditMouseEntered
        ImageIcon ic = new ImageIcon(getClass().getResource("/com/upiita/view/resources/pen-square-solid2.png"));
        iedit.setIcon(ic);
        bedit.setBackground(Bchange);
    }//GEN-LAST:event_beditMouseEntered

    private void beditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beditMouseExited
        ImageIcon ic = new ImageIcon(getClass().getResource("/com/upiita/view/resources/pen-square-solid.png"));
        iedit.setIcon(ic);
        bedit.setBackground(Bback);
    }//GEN-LAST:event_beditMouseExited

    private void bdelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bdelMousePressed
        bdel.setBackground(Bclick);
    }//GEN-LAST:event_bdelMousePressed

    private void beditMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beditMousePressed
        bedit.setBackground(Bclick);
    }//GEN-LAST:event_beditMousePressed

    private void bdelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bdelMouseReleased
        bdel.setBackground(Bback);
    }//GEN-LAST:event_bdelMouseReleased

    private void beditMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beditMouseReleased
        bedit.setBackground(Bback);
    }//GEN-LAST:event_beditMouseReleased

    private void beditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beditMouseClicked
        int[] filaSeleccionadas = TBDirectores.getSelectedRows();
        int noFilas = filaSeleccionadas.length;
        if (noFilas == 0) 
            JOptionPane.showMessageDialog(null, "Ingrese una fila para modificar", "CINETECA NACIONAL", HEIGHT,NIcon("/com/upiita/view/resources/advertencia.png"));
        else if (noFilas!=0 && noFilas!=1)
            JOptionPane.showMessageDialog(null, "Solo puede modificar una fila", "CINETECA NACIONAL",HEIGHT,NIcon("/com/upiita/view/resources/advertencia.png"));
        
        else {
            int filaSeleccionada = TBDirectores.getSelectedRows()[0];
            Edit_Directores Modificar;
            try {
                 if("0".equals(TBDirectores.getValueAt(TBDirectores.getSelectedRow(),2).toString())  )
                 JOptionPane.showMessageDialog(null, "No puede modificar un director desactivado", "CINETECA NACIONAL",HEIGHT,NIcon("/com/upiita/view/resources/advertencia.png"));
         
            else{
                Modificar = new Edit_Directores();
                Modificar.setNombre(TBDirectores.getValueAt(filaSeleccionada,0).toString());
                Modificar.fillGaps();
                Modificar.setVisible(true);
             }
            } catch (FontFormatException ex) {
                Logger.getLogger(_Directores.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_beditMouseClicked

    private void bdelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bdelMouseClicked
        int[] filaSeleccionadas = TBDirectores.getSelectedRows();
        int noFilas = filaSeleccionadas.length;
        if (noFilas == 0) {
            JOptionPane.showMessageDialog(null, "Ingrese una o varias filas para eliminar", "CINETECA NACIONAL", HEIGHT, NIcon("/com/upiita/view/resources/advertencia.png"));
        } else {
            int res = JOptionPane.showConfirmDialog(null, "¿Desea eliminar " + noFilas + " filas?", "CINETECA NACIONAL", JOptionPane.YES_NO_OPTION);
            if (res == 0) {
                System.out.println("Sentencia para borrar");
            }

            for (int fila : filaSeleccionadas) {
                String nombreDirector;
                nombreDirector = TBDirectores.getValueAt(fila,0).toString();
                directorDao.delete(nombreDirector);
//            SentenciasSQL.bajaRegistro(alumno, "Alumno", "curp");
            }
        }
    }//GEN-LAST:event_bdelMouseClicked

    private void txtNombreEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreEditActionPerformed

    private void txtBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusquedaActionPerformed

    private void txtBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyReleased

        sorter.setRowFilter((RowFilter.regexFilter("(?i)"+txtBusqueda.getText(),0)));
    }//GEN-LAST:event_txtBusquedaKeyReleased

    private void btnAltaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAltaMouseClicked
        String nombreDirector = txtNombreEdit.getText();
        Director newDirector = new Director(nombreDirector.toUpperCase());
        directorDao.create(newDirector);
        JOptionPane.showMessageDialog(null, "Alta exitosa", "CINETECA NACIONAL ", HEIGHT,NIcon("/com/upiita/view/resources/confirm.png"));
        txtNombreEdit.setText(" ");
        
    }//GEN-LAST:event_btnAltaMouseClicked

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAltaActionPerformed

    private void breactivarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_breactivarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_breactivarMouseClicked

    private void breactivarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_breactivarMouseEntered
        ImageIcon ic = new ImageIcon(getClass().getResource("/com/upiita/view/resources/reactivar2.png"));
        ireactivar.setIcon(ic);
        breactivar.setBackground(Bchange);
    }//GEN-LAST:event_breactivarMouseEntered

    private void breactivarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_breactivarMouseExited
        ImageIcon ic = new ImageIcon(getClass().getResource("/com/upiita/view/resources/reactivar.png"));
        ireactivar.setIcon(ic);
        breactivar.setBackground(Bback);
    }//GEN-LAST:event_breactivarMouseExited

    private void breactivarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_breactivarMousePressed
        breactivar.setBackground(Bclick);
    }//GEN-LAST:event_breactivarMousePressed

    private void breactivarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_breactivarMouseReleased
        int[] filaSeleccionadas = TBDirectores.getSelectedRows();
        int filaSeleccionada = 0;
        int noFilas = filaSeleccionadas.length;
        if (noFilas == 0) {
            JOptionPane.showMessageDialog(null, "Seleccione al menos una película para reactivar", "CINETECA NACIONAL", HEIGHT, NIcon("/com/upiita/view/resources/advertencia.png"));
        } else {
            int res = JOptionPane.showConfirmDialog(null, "¿Desea reactivar" + noFilas + " filas?", "CINETECA NACIONAL", HEIGHT, 1);
            if (res == 0) {
                filaSeleccionada = TBDirectores.getSelectedRows()[0];
                directorDao.reactive(TBDirectores.getValueAt(filaSeleccionada,0).toString().toUpperCase());
            }
        }
    }//GEN-LAST:event_breactivarMouseReleased
     public void headersDirectores() {
         int[] anchoCol = {300,1,1};
        int i = 0;
        for (int ancho : anchoCol) { // Implementa el arrego anchoCol en la tabla
            TableColumn column = TBDirectores.getColumnModel().getColumn(i++);
            column.setMinWidth(ancho);
            column.setMaxWidth(ancho);
            column.setPreferredWidth(ancho);
        }
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground( new Color(28,37,65) );
        for (int j = 0; j < TBDirectores.getModel().getColumnCount(); j++) {
            TBDirectores.getColumnModel().getColumn(j).setHeaderRenderer(headerRenderer);
        }
    }
    
     
      public Icon NIcon (String path){
        Icon image = new ImageIcon (getClass().getResource(path) );          
        return image;
    }
      
    public void fillDirectores() {
          
        int len = this.directores.size();
        // Inicializa la matriz modelo para mostrar en la tabla 
        String m[][] = new String[len > 0 ? len: 1][3];
        //LLena filas de la tabla con los datos del arrayList del archivo 
        for (int i = 0; i < len; i++) {
            m[i][0] = String.valueOf(directores.get(i).getNombre());
            m[i][1] = String.valueOf(directores.get(i).getIdDirector());
            m[i][2] = String.valueOf(directores.get(i).getEstado());
        }
        
        // Implementa la matriz en la tabla
        TBDirectores.setModel(new javax.swing.table.DefaultTableModel(
                m, new String[]{"Nombre","ID","Estado"}));
        headersDirectores();
         RowsRenderer rr = new RowsRenderer(2);
        TBDirectores.setDefaultRenderer(Object.class, rr);
    }
     
     
    Color change = new Color(111, 255, 233);
    Color Bchange = new Color(43, 59, 86);
    Color Bback = new Color(28, 37, 65);
    Color Bclick = new Color(11, 19, 43);
    Fuentes fonttype = new Fuentes (); 
    AnimationClass DirectoresU = new AnimationClass();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label;
    private javax.swing.JTable TBDirectores;
    private javax.swing.JPanel _Display;
    private javax.swing.JPanel bdel;
    private javax.swing.JPanel bedit;
    private javax.swing.JPanel breactivar;
    private javax.swing.JButton btnAlta;
    private javax.swing.JLabel idel;
    private javax.swing.JLabel iedit;
    private javax.swing.JLabel ireactivar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelAdd;
    private javax.swing.JLabel txtAltas;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JLabel txtName;
    private javax.swing.JTextField txtNombreEdit;
    // End of variables declaration//GEN-END:variables
}
