/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.upiita.view;

import AppPackage.AnimationClass;
import com.upiita.view.fonts.Fuentes;
import java.awt.Font;
import java.awt.FontFormatException;

/**
 *
 * @author Gallegosr
 */
public class Cat_Peliculas extends javax.swing.JPanel {

    /**
     * Creates new form Cat_Peliculas
     */
    public Cat_Peliculas() throws FontFormatException {
        initComponents();
        
        //jPanelLabels.setBackground(new Color (255,255,255,14));
        Font Lovelo = fonttype.nFont(fonttype.getLovelo() , 1,38);
        Font Lemon = fonttype.nFont(fonttype.getLemon() , 1,10);
        Font Glacial = fonttype.nFont(fonttype.getGlacial() , 1,17);
        jLabelTitulo.setFont(Lovelo);
        
        rbNoIdentificado.setFont(Glacial);
        cbDirector.setFont(Glacial);
        cbPais.setFont(Glacial);
        btnAlta.setFont(Lemon);
        
        
         AnimationClass PeliculasR = new AnimationClass();
        javax.swing.JLabel[] labels = new javax.swing.JLabel[5];
        
        labels [0]= jLabelTitle0;
        labels [1]= jLabelDirector;
        labels [2]= jLabelPais;
        labels [3]= jLabelTitle;
        labels [4]= jLabelYear;
        
        for (javax.swing.JLabel label : labels) {
            label.setFont(Glacial);
            PeliculasR.jLabelXRight(0, 150, 30, 10, label);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        rbNoIdentificado = new javax.swing.JRadioButton();
        jLabelTitle = new javax.swing.JLabel();
        jLabelPais = new javax.swing.JLabel();
        cbPais = new javax.swing.JComboBox<>();
        jTextFieldTitle = new javax.swing.JTextField();
        jLabelYear = new javax.swing.JLabel();
        cbDirector = new javax.swing.JComboBox<>();
        jLabelTitle0 = new javax.swing.JLabel();
        jLabelDirector = new javax.swing.JLabel();
        txtYear = new javax.swing.JTextField();
        btnAlta = new javax.swing.JButton();

        jLabel5.setText("Título Original");

        setBackground(new java.awt.Color(58, 80, 107));
        setLayout(null);

        jLabelTitulo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("ALTAS PELÍCULAS");
        jLabelTitulo.setName("jLabelTitulo"); // NOI18N
        add(jLabelTitulo);
        jLabelTitulo.setBounds(240, 10, 426, 60);

        jTextField1.setToolTipText("");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1);
        jTextField1.setBounds(430, 100, 171, 24);

        rbNoIdentificado.setForeground(new java.awt.Color(255, 255, 255));
        rbNoIdentificado.setText("<html><center>No <p> identificado<center><html>");
        rbNoIdentificado.setOpaque(false);
        rbNoIdentificado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNoIdentificadoActionPerformed(evt);
            }
        });
        add(rbNoIdentificado);
        rbNoIdentificado.setBounds(610, 190, 120, 90);

        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setText("Título de Exhibición");
        add(jLabelTitle);
        jLabelTitle.setBounds(0, 150, 160, 50);

        jLabelPais.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPais.setText("País");
        add(jLabelPais);
        jLabelPais.setBounds(0, 330, 160, 50);

        cbPais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPaisActionPerformed(evt);
            }
        });
        add(cbPais);
        cbPais.setBounds(430, 340, 170, 26);

        jTextFieldTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTitleActionPerformed(evt);
            }
        });
        add(jTextFieldTitle);
        jTextFieldTitle.setBounds(430, 160, 171, 24);

        jLabelYear.setForeground(new java.awt.Color(255, 255, 255));
        jLabelYear.setText("Año");
        add(jLabelYear);
        jLabelYear.setBounds(0, 210, 160, 50);

        cbDirector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cbDirector);
        cbDirector.setBounds(430, 280, 170, 26);

        jLabelTitle0.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle0.setText("Título Original");
        add(jLabelTitle0);
        jLabelTitle0.setBounds(0, 90, 160, 50);

        jLabelDirector.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDirector.setText("Director");
        add(jLabelDirector);
        jLabelDirector.setBounds(0, 270, 160, 50);

        txtYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtYearActionPerformed(evt);
            }
        });
        add(txtYear);
        txtYear.setBounds(430, 220, 171, 24);

        btnAlta.setBackground(new java.awt.Color(28, 37, 65));
        btnAlta.setForeground(new java.awt.Color(255, 255, 255));
        btnAlta.setText("DAR DE ALTA");
        add(btnAlta);
        btnAlta.setBounds(300, 420, 190, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void rbNoIdentificadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNoIdentificadoActionPerformed
        if(rbNoIdentificado.isSelected())
            txtYear.setVisible(false);
        else
            txtYear.setVisible(true);
    }//GEN-LAST:event_rbNoIdentificadoActionPerformed

    private void cbPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPaisActionPerformed

    private void txtYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYearActionPerformed

    private void jTextFieldTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTitleActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    
      Fuentes fonttype = new Fuentes ();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlta;
    private javax.swing.JComboBox<String> cbDirector;
    private javax.swing.JComboBox<String> cbPais;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelDirector;
    private javax.swing.JLabel jLabelPais;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelTitle0;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelYear;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldTitle;
    private javax.swing.JRadioButton rbNoIdentificado;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
