/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.upiita.view;

import AppPackage.AnimationClass;
import com.upiita.view.fonts.Fuentes;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Gallegosr
 */
public class Edit_Peliculas extends javax.swing.JFrame {

    public String TituloOriginal;
    public String TituloExhibicion;
    public String Anio;
    public String Director;
    public String Pais;
    public String ID;
    
    
    
    /**
     * Creates new form Edit_Peliculas
     */
    public Edit_Peliculas() throws FontFormatException {
        this.setLocationRelativeTo(null);
        
        setLocation(600, 300);
        setUndecorated(true);
        
        this.setBackground(Color.yellow);
        
        initComponents();
        Font Lovelo = fonttype.nFont(fonttype.getLovelo() ,1,20);
        Font Glacial = fonttype.nFont(fonttype.getGlacial(),1,17);
        Font Lemon = fonttype.nFont(fonttype.getLemon() , 1,9);
        Font Lemon2 = fonttype.nFont(fonttype.getLemon(), 1, 7);
        jLabelTitulo.setFont(Lovelo);
        
        Space.setFont(Lemon2);
        rbNoIdentificado.setFont(Glacial);
        cbDirector.setFont(Glacial);
        cbPais.setFont(Glacial);
        txtTituloOriginal.setFont(Glacial);
        txtTituloEx.setFont(Glacial);
        txtYear.setFont(Glacial);
        btnModificar.setFont(Lemon);
        
        
        
        txtTituloOriginal.setFont(Glacial);
        txtTituloEx.setFont(Glacial);
            txtYear.setFont(Glacial);
        
        
        
        javax.swing.JLabel[] labels = new javax.swing.JLabel[5];
        
        labels[0] = jLabelDirector;
        labels[1] = jLabelPais;
        labels[2] = jLabelTitle;
        labels[3] = jLabelTitle1;
        labels[4] = jLabelYear;
        
        for (javax.swing.JLabel label : labels) {
            label.setFont(Glacial);
            PeliculasR.jLabelXRight(0, 150, 30, 10, label);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Space = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        txtTituloEx = new javax.swing.JTextField();
        rbNoIdentificado = new javax.swing.JRadioButton();
        jLabelYear = new javax.swing.JLabel();
        jLabelTitle1 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        txtTituloOriginal = new javax.swing.JTextField();
        cbPais = new javax.swing.JComboBox<>();
        cbDirector = new javax.swing.JComboBox<>();
        jLabelPais = new javax.swing.JLabel();
        jLabelDirector = new javax.swing.JLabel();
        txtYear = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(58, 80, 107));
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(11, 19, 43));
        jPanel3.setMinimumSize(new java.awt.Dimension(100, 50));
        jPanel3.setPreferredSize(new java.awt.Dimension(900, 24));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.setLayout(null);

        jPanel5.setBackground(new java.awt.Color(11, 19, 43));
        jPanel5.setPreferredSize(new java.awt.Dimension(32, 24));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel5MouseExited(evt);
            }
        });
        jPanel5.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/upiita/view/Resources/tache.png"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(18, 24));
        jPanel5.add(jLabel2);
        jLabel2.setBounds(10, 0, 20, 24);

        jPanel3.add(jPanel5);
        jPanel5.setBounds(780, 0, 50, 24);

        Space.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        Space.setForeground(new java.awt.Color(255, 255, 255));
        Space.setText("Editar Pelicula - Base de datos");
        Space.setPreferredSize(new java.awt.Dimension(37, 24));
        jPanel3.add(Space);
        Space.setBounds(10, 0, 340, 20);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 830, 24);

        jPanel1.setBackground(new java.awt.Color(58, 80, 107));
        jPanel1.setLayout(null);

        jLabelTitulo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Editar Pelicula");
        jLabelTitulo.setName("jLabelTitulo"); // NOI18N
        jPanel1.add(jLabelTitulo);
        jLabelTitulo.setBounds(290, 60, 250, 60);

        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setText("Título de Exhibición");
        jPanel1.add(jLabelTitle);
        jLabelTitle.setBounds(0, 220, 120, 25);

        txtTituloEx.setForeground(new java.awt.Color(0, 0, 0));
        txtTituloEx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloExActionPerformed(evt);
            }
        });
        jPanel1.add(txtTituloEx);
        txtTituloEx.setBounds(350, 220, 230, 24);

        rbNoIdentificado.setForeground(new java.awt.Color(255, 255, 255));
        rbNoIdentificado.setSelected(true);
        rbNoIdentificado.setText("<html> <center> No <p> identificado <center> <html>");
        rbNoIdentificado.setOpaque(false);
        rbNoIdentificado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNoIdentificadoActionPerformed(evt);
            }
        });
        jPanel1.add(rbNoIdentificado);
        rbNoIdentificado.setBounds(640, 270, 160, 50);

        jLabelYear.setForeground(new java.awt.Color(255, 255, 255));
        jLabelYear.setText("Año");
        jPanel1.add(jLabelYear);
        jLabelYear.setBounds(0, 280, 120, 25);

        jLabelTitle1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle1.setText("Título Original");
        jPanel1.add(jLabelTitle1);
        jLabelTitle1.setBounds(0, 160, 120, 25);

        btnModificar.setBackground(new java.awt.Color(28, 37, 65));
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar);
        btnModificar.setBounds(350, 440, 170, 32);

        txtTituloOriginal.setForeground(new java.awt.Color(0, 0, 0));
        txtTituloOriginal.setToolTipText("");
        txtTituloOriginal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloOriginalActionPerformed(evt);
            }
        });
        jPanel1.add(txtTituloOriginal);
        txtTituloOriginal.setBounds(350, 160, 230, 24);

        cbPais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPaisActionPerformed(evt);
            }
        });
        jPanel1.add(cbPais);
        cbPais.setBounds(350, 380, 230, 30);

        cbDirector.setEditable(true);
        cbDirector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbDirector);
        cbDirector.setBounds(350, 330, 230, 30);

        jLabelPais.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPais.setText("País");
        jPanel1.add(jLabelPais);
        jLabelPais.setBounds(0, 380, 120, 25);

        jLabelDirector.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDirector.setText("Director");
        jPanel1.add(jLabelDirector);
        jLabelDirector.setBounds(0, 330, 120, 25);

        txtYear.setForeground(new java.awt.Color(0, 0, 0));
        txtYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtYearActionPerformed(evt);
            }
        });
        jPanel1.add(txtYear);
        txtYear.setBounds(350, 280, 230, 24);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-4, -4, 850, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbNoIdentificadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNoIdentificadoActionPerformed
       if(rbNoIdentificado.isSelected())
            txtYear.setVisible(false);
        else
            txtYear.setVisible(true);
    }//GEN-LAST:event_rbNoIdentificadoActionPerformed

    private void cbPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPaisActionPerformed

    private void txtTituloExActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloExActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloExActionPerformed

    private void txtYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYearActionPerformed

    private void txtTituloOriginalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloOriginalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloOriginalActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
       String Titulo = jLabelTitle.getText().toUpperCase();

    }//GEN-LAST:event_btnModificarActionPerformed

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        int res = JOptionPane.showConfirmDialog(null, "¿Desea salir de la edición? \n No se guardaran los cambios", "CINETECA NACIONAL ", JOptionPane.YES_NO_OPTION);
        if(res == 0){
            this.setVisible(false);
        }
        else;
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jPanel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseEntered
        Color CrossBg = new Color(200,0,0);
        jPanel5.setBackground(CrossBg);
    }//GEN-LAST:event_jPanel5MouseEntered

    private void jPanel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseExited
        Color CrossBg = new Color(11,19,43);
        jPanel5.setBackground(CrossBg);
    }//GEN-LAST:event_jPanel5MouseExited

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xx, y - yy);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit_Peliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit_Peliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit_Peliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit_Peliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Edit_Peliculas().setVisible(true);
                } catch (FontFormatException ex) {
                    Logger.getLogger(Edit_Peliculas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    public void fillGaps (){
        txtTituloOriginal.setText(TituloOriginal);
        txtTituloEx.setText(TituloExhibicion);
        txtYear.setText(Anio);
}
     static int xx, yy;
    Fuentes fonttype = new Fuentes ();  
    AnimationClass PeliculasR = new AnimationClass();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Space;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cbDirector;
    private javax.swing.JComboBox<String> cbPais;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelDirector;
    private javax.swing.JLabel jLabelPais;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelTitle1;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelYear;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton rbNoIdentificado;
    private javax.swing.JTextField txtTituloEx;
    private javax.swing.JTextField txtTituloOriginal;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
